package edu.utap.watchlist.api

//MAPS COUNTRY NAMES TO COUNTRY CODES
object Countries {

    val countriesMap = mapOf(
        "United States" to "US",
        "U.A.E" to "AE",
        "Algeria" to "DZ",
        "Armenia" to "AM",
        "Argentina" to "AR",
        "Austria" to "AT",
        "Australia" to "AU",
        "China" to "CN",
        "Croatia" to "BA",
        "Czech" to "CZ",
        "Barbados" to "BB",
        "Belgium" to "BE",
        "Bulgaria" to "BG",
        "Bolivia" to "BO",
        "Bahamas" to "BS",
        "Canada" to "CA",
        "Switzerland" to "CH",
        "Côte d'Ivoire" to "CI",
        "Colombia" to "CO",
        "Costa Rica" to "CR",
        "Czechia" to "CZ",
        "Danish" to "DK",
        "Dominican Republic" to "DO",
        "Egypt" to "EG",
        "Ecuador" to "EC",
        "United Kingdom" to "GB",
        "French Guiana" to "GF",
        "Ghana" to "GH",
        "Equatorial Guinea" to "GQ",
        "Guatemala" to "GT",
        "Hong Kong" to "HK",
        "Honduras" to "HN",
        "Ireland" to "IE",
        "Israel" to "IL",
        "India" to "IN",
        "Iraq" to "IQ",
        "Jamaica" to "JM",
        "Kenya" to "KE",
        "Lebanon" to "LB",
        "Libya" to "LY",
        "Moldova" to "MD",
        "Mauritius" to "MU",
        "Mexico" to "MX",
        "Malaysia" to "MY",
        "Mozambique" to "MZ",
        "Niger" to "NE",
        "Nigeria" to "NG",
        "Norway" to "NO",
        "Panama" to "PA",
        "Peru" to "PE",
        "Philippines" to "PH",
        "Palestine" to "PS",
        "Portugal" to "PT",
        "Paraguay" to "PY",
        "Romania" to "RO",
        "Seychelles" to "SC",
        "Singapore" to "SG",
        "Senegal" to "SN",
        "El Salvador" to "SV",
        "Trinidad and Tobago" to "TT",
        "Tanzania" to "TZ",
        "Uganda" to "UG",
        "Uruguay" to "UY",
        "Uruguay" to "VE",
        "Uruguay" to "ZM",
        "Saudi Arabia" to "SA",
        "Catalan" to "ES",
        "Taiwan" to "TW",
        "Germany" to "DE",
        "Greek" to "GR",
        "Spain" to "ES",
        "Finland" to "FI",
        "France" to "FR",
        "Hungary" to "HU",
        "Iceland" to "IS",
        "Italy" to "IT",
        "Japan" to "JP",
        "Korea" to "KR",
        "Netherlands" to "NL",
        "Poland" to "PL",
        "Portugal" to "BR",
        "Romania" to "RN",
        "Russia" to "RU",
        "Croatia" to "HR",
        "Slovakia" to "SK",
        "Albania" to "AL",
        "Sweden" to "SE",
        "Thailand" to "TH",
        "Turkey" to "TR",
        "Pakistan" to "PK",
        "Indonesia" to "ID",
        "Ukraine" to "UA",
        "Belarus" to "BY",
        "Slovenia" to "SI",
        "Estonia" to "EE",
        "Latvia" to "LV",
        "Lithuania" to "LT",
        "Vietnam" to "VN",
        "South Africa" to "ZA"
    )

}