package edu.utap.watchlist.api

//MAPS LANGUAGE NAMES TO LANGUAGE CODES
object Languages {

    val languageMap = mapOf("English" to "en",
        "All" to "",
        "Abkhazian" to "ab",
        "Afar" to "aa",
        "Afrikaans" to "af",
        "Akan" to "ak",
        "Albanian" to "sq",
        "Amharic" to "am",
        "Aragonese" to "",
        "Armenian" to "",
        "Assamese" to "",
        "Avaric" to "",
        "Avestan" to "",
        "Aymara" to "",
        "Azerbaijani" to "",
        "Bambara" to "",
        "Bashkir" to "",
        "Basque" to "eu",
        "Belarusian" to "",
        "Bengali" to "",
        "Bislama" to "",
        "Bosnian" to "",
        "Breton" to "",
        "Bulgarian" to "",
        "Burmese" to "",
        "Catalan" to "ca",
        "Chamorro" to "",
        "Chechen" to "",
        "Chichewa" to "ny",
        "Chinese" to "zh",
        "Church Slavonic" to "",
        "Chuvash" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "",
        "" to "")
}